//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Iletisim
    {
        public int Id { get; set; }
        public string Adres { get; set; }
        public string Website { get; set; }
        public string Telefon { get; set; }
        public string Telefon2 { get; set; }
        public int FirmaId { get; set; }
    
        public virtual Firmalar Firmalar { get; set; }
    }
}
