//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Banka
    {
        public int Id { get; set; }
        public string Iban { get; set; }
        public string SubeKodu { get; set; }
        public string BankaAdi { get; set; }
        public Nullable<int> FirmaId { get; set; }
    
        public virtual Firmalar Firmalar { get; set; }
    }
}
